### ISSUE TITLE
tcltls not loading

### ISSUE THREAD

**Issue by TorstenEdler** [teclab-at/tcltk#4]
When I issue the command 
   `package require tlc`
i get
   `couldn't load library "C:/Daten/TE/TCL/TombertTcl/lib/tcltls1.8.0/tcltls.dll": this library or a dependent library could not be found in library path`
while this particular file is present. This happens with tclsh.exe/wish.exe and tclsh86.exe/wish86.exe. 

I just downloaded and un-tgz-ed the version "tcltk86-8.6.12.8.tcl86_visa.Win10.x86_64.tgz"

**Comment by teclab-at** [comment]
Maybe the ssl library is not in the search path.
You should have a share/lib64 folder with all necessary libs, either

- copy them to the bin folder
- copy them to your windows/system folder
- append the lib64 folder to your windows PATH environment variable
