### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by milen-prg** [teclab-at/tcltk#8]
I download your precompiled Tlc/Tk distribution for windows: tcltk87-8.7a6.15.tcl87.Win10.x86_64
And try to start some of the tools:

\tcltk87-8.7a6.15.tcl87.Win10.x86_64\bin>tclsh page.tcl
can't read "tcl_pkgPath": no such variable
    while executing
"lindex $tcl_pkgPath end"
    invoked from within
"file join [lindex $tcl_pkgPath end] page"
    invoked from within
"lappend auto_path [file join [lindex $tcl_pkgPath end] page]"
    (file "page.tcl" line 26)

The scripts do not start, but error:
can't read "tcl_pkgPath": no such variable

P.S. I'm on Windows 10 Pro 64bit

**Comment by teclab-at** [comment]
See here: https://wiki.tcl-lang.org/page/tcl_pkgPath

What was your intention to run page.tcl?

**Comment by teclab-at** [comment]
You are on the wrong path. For running PAGE you need Python. This page.tcl has nothing to do with it.
If you want to start with tcl/tk, then start here: https://www.tutorialspoint.com/tcl-tk/index.htm
